# Site settings
title: 925 Türkçe Sözcük için Duyu Normları
description: Kumcu & Yağlı
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Türkçe Sözcükler için Duyu Normları
user_description: 
user_title: Kumcu & Yağlı
email: 925sozcuk@gmail.com
# twitter_username: alperkumcu
# github_username: 925sozcuk

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
